[package]
name = "xmake_wrapper"
version = "0.1.0"
edition = "2024"

[dependencies]

# external
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio-util.workspace = true
log.workspace = true